-- MySQL Script generated by MySQL Workbench
-- Thu Sep 28 12:13:24 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizzeria` DEFAULT CHARACTER SET utf8mb3 ;
-- -----------------------------------------------------
-- Schema optical_store
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema optical_store
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `optical_store` DEFAULT CHARACTER SET utf8mb3 ;
USE `pizzeria` ;

-- -----------------------------------------------------
-- Table `pizzeria`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`address` (
  `id` INT NOT NULL,
  `street` VARCHAR(45) NULL DEFAULT NULL,
  `number` INT NULL DEFAULT NULL,
  `floor` INT NULL DEFAULT NULL,
  `door` INT NULL DEFAULT NULL,
  `city` VARCHAR(45) NULL DEFAULT NULL,
  `postal code` INT NULL DEFAULT NULL,
  `country` INT NULL DEFAULT NULL,
  `type` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pizzeria`.`Supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`Supplier` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL COMMENT '\\n',
  `telephone` INT NULL DEFAULT NULL,
  `fax` INT NULL DEFAULT NULL,
  `nif` VARCHAR(45) NULL DEFAULT NULL,
  `address_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Supplier_address1_idx` (`address_id` ASC) VISIBLE,
  CONSTRAINT `fk_Supplier_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `pizzeria`.`address` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pizzeria`.`Brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`Brand` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `supplier_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `supplier_id_idx` (`supplier_id` ASC) VISIBLE,
  CONSTRAINT `supplier_id`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `pizzeria`.`Supplier` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pizzeria`.`Recommended`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`Recommended` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pizzeria`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`Customer` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `adress` VARCHAR(45) NULL DEFAULT NULL,
  `telephone` INT NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `registration_date` DATE NULL DEFAULT NULL,
  `Recommended_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Customer_Recommended1_idx` (`Recommended_id` ASC) VISIBLE,
  CONSTRAINT `fk_Customer_Recommended1`
    FOREIGN KEY (`Recommended_id`)
    REFERENCES `pizzeria`.`Recommended` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pizzeria`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`Employee` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pizzeria`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`Product` (
  `id` INT NOT NULL,
  `graduation` VARCHAR(45) NULL DEFAULT NULL,
  `type` VARCHAR(45) NULL DEFAULT NULL,
  `frame_color` VARCHAR(45) NULL DEFAULT NULL,
  `glass_color` VARCHAR(45) NULL DEFAULT NULL,
  `price` DOUBLE NULL DEFAULT NULL,
  `brand_id` INT NOT NULL,
  `stock` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `brand_id_idx` (`brand_id` ASC) VISIBLE,
  CONSTRAINT `brand_id`
    FOREIGN KEY (`brand_id`)
    REFERENCES `pizzeria`.`Brand` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pizzeria`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`Order` (
  `id` INT NOT NULL,
  `date` DATE NULL DEFAULT NULL,
  `total_sale` DOUBLE NULL DEFAULT NULL,
  `Employee_id` INT NOT NULL,
  `Customer_id` INT NOT NULL,
  `Product_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Order_Employee1_idx` (`Employee_id` ASC) VISIBLE,
  INDEX `fk_Order_Customer1_idx` (`Customer_id` ASC) VISIBLE,
  INDEX `fk_Order_Product1_idx` (`Product_id` ASC) VISIBLE,
  CONSTRAINT `fk_Order_Customer1`
    FOREIGN KEY (`Customer_id`)
    REFERENCES `pizzeria`.`Customer` (`id`),
  CONSTRAINT `fk_Order_Employee1`
    FOREIGN KEY (`Employee_id`)
    REFERENCES `pizzeria`.`Employee` (`id`),
  CONSTRAINT `fk_Order_Product1`
    FOREIGN KEY (`Product_id`)
    REFERENCES `pizzeria`.`Product` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

USE `optical_store` ;

-- -----------------------------------------------------
-- Table `optical_store`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optical_store`.`address` (
  `id` INT NOT NULL,
  `street` VARCHAR(45) NULL DEFAULT NULL,
  `number` INT NULL DEFAULT NULL,
  `floor` INT NULL DEFAULT NULL,
  `door` INT NULL DEFAULT NULL,
  `city` VARCHAR(45) NULL DEFAULT NULL,
  `postal code` INT NULL DEFAULT NULL,
  `country` INT NULL DEFAULT NULL,
  `type` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `optical_store`.`Supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optical_store`.`Supplier` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL COMMENT '\\n',
  `telephone` INT NULL DEFAULT NULL,
  `fax` INT NULL DEFAULT NULL,
  `nif` VARCHAR(45) NULL DEFAULT NULL,
  `address_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Supplier_address1_idx` (`address_id` ASC) VISIBLE,
  CONSTRAINT `fk_Supplier_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `optical_store`.`address` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `optical_store`.`Brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optical_store`.`Brand` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `supplier_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `supplier_id_idx` (`supplier_id` ASC) VISIBLE,
  CONSTRAINT `supplier_id`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `optical_store`.`Supplier` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `optical_store`.`Recommended`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optical_store`.`Recommended` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `optical_store`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optical_store`.`Customer` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `adress` VARCHAR(45) NULL DEFAULT NULL,
  `telephone` INT NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `registration_date` DATE NULL DEFAULT NULL,
  `Recommended_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Customer_Recommended1_idx` (`Recommended_id` ASC) VISIBLE,
  CONSTRAINT `fk_Customer_Recommended1`
    FOREIGN KEY (`Recommended_id`)
    REFERENCES `optical_store`.`Recommended` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `optical_store`.`store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optical_store`.`store` (
  `id` INT NOT NULL,
  `address` VARCHAR(45) NULL DEFAULT NULL,
  `postal_code` INT NULL DEFAULT NULL,
  `town` VARCHAR(45) NULL DEFAULT NULL,
  `province` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `optical_store`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optical_store`.`Employee` (
  `id` INT NOT NULL,
  `first_name` VARCHAR(45) NULL DEFAULT NULL,
  `store_id` INT NOT NULL,
  `type` ENUM("cook", "deliveryman") NULL,
  `last_name` VARCHAR(45) NULL,
  `nif` VARCHAR(45) NULL,
  `telephone` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Employee_store1_idx` (`store_id` ASC) VISIBLE,
  CONSTRAINT `fk_Employee_store1`
    FOREIGN KEY (`store_id`)
    REFERENCES `optical_store`.`store` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `optical_store`.`home delivery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optical_store`.`home delivery` (
  `id` INT NOT NULL,
  `order_id` INT NOT NULL,
  `time` DATETIME NULL DEFAULT NULL,
  `Employee_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_home delivery_order1_idx` (`order_id` ASC) VISIBLE,
  INDEX `fk_home delivery_Employee1_idx` (`Employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_home delivery_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `optical_store`.`order` (`id`),
  CONSTRAINT `fk_home delivery_Employee1`
    FOREIGN KEY (`Employee_id`)
    REFERENCES `optical_store`.`Employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `optical_store`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optical_store`.`Order` (
  `id` INT NOT NULL,
  `date` DATE NULL DEFAULT NULL,
  `total_sale` DOUBLE NULL DEFAULT NULL,
  `Customer_id` INT NOT NULL,
  `store_id` INT NOT NULL,
  `delivery__type` ENUM("pickup", "delivery") NULL,
  `home delivery_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Order_Customer1_idx` (`Customer_id` ASC) VISIBLE,
  INDEX `fk_Order_store1_idx` (`store_id` ASC) VISIBLE,
  INDEX `fk_Order_home delivery1_idx` (`home delivery_id` ASC) VISIBLE,
  CONSTRAINT `fk_Order_Customer1`
    FOREIGN KEY (`Customer_id`)
    REFERENCES `optical_store`.`Customer` (`id`),
  CONSTRAINT `fk_Order_store1`
    FOREIGN KEY (`store_id`)
    REFERENCES `optical_store`.`store` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_home delivery1`
    FOREIGN KEY (`home delivery_id`)
    REFERENCES `optical_store`.`home delivery` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `optical_store`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optical_store`.`category` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `optical_store`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optical_store`.`Product` (
  `id` INT NOT NULL,
  `graduation` VARCHAR(45) NULL DEFAULT NULL,
  `type` ENUM("pizza", "burger", "drink") NULL DEFAULT NULL,
  `frame_color` VARCHAR(45) NULL DEFAULT NULL,
  `glass_color` VARCHAR(45) NULL DEFAULT NULL,
  `price` DOUBLE NULL DEFAULT NULL,
  `brand_id` INT NOT NULL,
  `stock` INT NULL DEFAULT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `brand_id_idx` (`brand_id` ASC) VISIBLE,
  INDEX `fk_Product_category1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `brand_id`
    FOREIGN KEY (`brand_id`)
    REFERENCES `optical_store`.`Brand` (`id`),
  CONSTRAINT `fk_Product_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `optical_store`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `optical_store`.`pick_up`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optical_store`.`pick_up` (
  `id` INT NOT NULL,
  `order_id` INT NOT NULL,
  `time` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pick_up_order1_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `fk_pick_up_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `optical_store`.`order` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `optical_store`.`pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optical_store`.`pizza` (
  `category_id` INT NOT NULL,
  `Product_id` INT NOT NULL,
  PRIMARY KEY (`category_id`, `Product_id`),
  INDEX `fk_Pizza_category1_idx` (`category_id` ASC) VISIBLE,
  INDEX `fk_Pizza_Product1_idx` (`Product_id` ASC) VISIBLE,
  CONSTRAINT `fk_Pizza_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `optical_store`.`category` (`id`),
  CONSTRAINT `fk_Pizza_Product1`
    FOREIGN KEY (`Product_id`)
    REFERENCES `optical_store`.`product` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `optical_store`.`Product_has_Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optical_store`.`Product_has_Order` (
  `Product_id` INT NOT NULL,
  `Order_id` INT NOT NULL,
  `quantity` INT NULL,
  PRIMARY KEY (`Product_id`, `Order_id`),
  INDEX `fk_Product_has_Order_Order1_idx` (`Order_id` ASC) VISIBLE,
  INDEX `fk_Product_has_Order_Product1_idx` (`Product_id` ASC) VISIBLE,
  CONSTRAINT `fk_Product_has_Order_Product1`
    FOREIGN KEY (`Product_id`)
    REFERENCES `optical_store`.`Product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_has_Order_Order1`
    FOREIGN KEY (`Order_id`)
    REFERENCES `optical_store`.`Order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
