-- MySQL Script generated by MySQL Workbench
-- Thu Sep 21 14:34:58 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema optical_store
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema optical_store
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `optical_store` DEFAULT CHARACTER SET utf8 ;
USE `optical_store` ;

-- -----------------------------------------------------
-- Table `optical_store`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optical_store`.`address` (
  `id` INT NOT NULL,
  `street` VARCHAR(45) NULL,
  `number` INT NULL,
  `floor` INT NULL,
  `door` INT NULL,
  `city` VARCHAR(45) NULL,
  `postal code` INT NULL,
  `country` INT NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optical_store`.`Supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optical_store`.`Supplier` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL COMMENT '\n',
  `telephone` INT NULL,
  `fax` INT NULL,
  `nif` VARCHAR(45) NULL,
  `address_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Supplier_address1_idx` (`address_id` ASC) VISIBLE,
  CONSTRAINT `fk_Supplier_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `optical_store`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optical_store`.`Recommended`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optical_store`.`Recommended` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optical_store`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optical_store`.`Customer` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `adress` VARCHAR(45) NULL,
  `telephone` INT NULL,
  `email` VARCHAR(45) NULL,
  `registration_date` DATE NULL,
  `Recommended_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Customer_Recommended1_idx` (`Recommended_id` ASC) VISIBLE,
  CONSTRAINT `fk_Customer_Recommended1`
    FOREIGN KEY (`Recommended_id`)
    REFERENCES `optical_store`.`Recommended` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optical_store`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optical_store`.`Employee` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optical_store`.`Brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optical_store`.`Brand` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `supplier_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `supplier_id_idx` (`supplier_id` ASC) VISIBLE,
  CONSTRAINT `supplier_id`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `optical_store`.`Supplier` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optical_store`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optical_store`.`Product` (
  `id` INT NOT NULL,
  `graduation` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `frame_color` VARCHAR(45) NULL,
  `glass_color` VARCHAR(45) NULL,
  `price` REAL NULL,
  `brand_id` INT NOT NULL,
  `stock` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `brand_id_idx` (`brand_id` ASC) VISIBLE,
  CONSTRAINT `brand_id`
    FOREIGN KEY (`brand_id`)
    REFERENCES `optical_store`.`Brand` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optical_store`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optical_store`.`Order` (
  `id` INT NOT NULL,
  `date` DATE NULL,
  `total_sale` REAL NULL,
  `Employee_id` INT NOT NULL,
  `Customer_id` INT NOT NULL,
  `Product_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Order_Employee1_idx` (`Employee_id` ASC) VISIBLE,
  INDEX `fk_Order_Customer1_idx` (`Customer_id` ASC) VISIBLE,
  INDEX `fk_Order_Product1_idx` (`Product_id` ASC) VISIBLE,
  CONSTRAINT `fk_Order_Employee1`
    FOREIGN KEY (`Employee_id`)
    REFERENCES `optical_store`.`Employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Customer1`
    FOREIGN KEY (`Customer_id`)
    REFERENCES `optical_store`.`Customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Product1`
    FOREIGN KEY (`Product_id`)
    REFERENCES `optical_store`.`Product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optical_store`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optical_store`.`category` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `optical_store`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optical_store`.`customer` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `postal_code` INT NULL,
  `city` VARCHAR(45) NULL,
  `province` VARCHAR(45) NULL,
  `telephone` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optical_store`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optical_store`.`product` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `image` INT NULL,
  `price` REAL NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optical_store`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optical_store`.`item` (
  `id` INT NOT NULL,
  `quantity` INT NULL,
  `Product_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_item_Product1_idx` (`Product_id` ASC) VISIBLE,
  CONSTRAINT `fk_item_Product1`
    FOREIGN KEY (`Product_id`)
    REFERENCES `optical_store`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optical_store`.`store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optical_store`.`store` (
  `id` INT NOT NULL,
  `address` VARCHAR(45) NULL,
  `postal_code` INT NULL,
  `town` VARCHAR(45) NULL,
  `province` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optical_store`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optical_store`.`order` (
  `id` INT NOT NULL,
  `date` DATE NULL,
  `delivery_type` VARCHAR(45) NULL,
  `total_price` VARCHAR(45) NULL,
  `item_id` INT NOT NULL,
  `Customer_id` INT NOT NULL,
  `store_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Order_item1_idx` (`item_id` ASC) VISIBLE,
  INDEX `fk_Order_Customer2_idx` (`Customer_id` ASC) VISIBLE,
  INDEX `fk_order_store1_idx` (`store_id` ASC) VISIBLE,
  CONSTRAINT `fk_Order_item1`
    FOREIGN KEY (`item_id`)
    REFERENCES `optical_store`.`item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Customer2`
    FOREIGN KEY (`Customer_id`)
    REFERENCES `optical_store`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_store1`
    FOREIGN KEY (`store_id`)
    REFERENCES `optical_store`.`store` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optical_store`.`pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optical_store`.`pizza` (
  `category_id` INT NOT NULL,
  `Product_id` INT NOT NULL,
  PRIMARY KEY (`category_id`, `Product_id`),
  INDEX `fk_Pizza_category1_idx` (`category_id` ASC) VISIBLE,
  INDEX `fk_Pizza_Product1_idx` (`Product_id` ASC) VISIBLE,
  CONSTRAINT `fk_Pizza_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `optical_store`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pizza_Product1`
    FOREIGN KEY (`Product_id`)
    REFERENCES `optical_store`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optical_store`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optical_store`.`employee` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `nif` INT NULL,
  `telephone` INT NULL,
  `type` VARCHAR(45) NULL,
  `store_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_employee_store1_idx` (`store_id` ASC) VISIBLE,
  CONSTRAINT `fk_employee_store1`
    FOREIGN KEY (`store_id`)
    REFERENCES `optical_store`.`store` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optical_store`.`deliveryman`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optical_store`.`deliveryman` (
  `id` INT NOT NULL,
  `employee_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_delivery_employee1_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_delivery_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `optical_store`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optical_store`.`cook`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optical_store`.`cook` (
  `id` INT NOT NULL,
  `employee_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cook_employee1_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_cook_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `optical_store`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optical_store`.`hamburger`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optical_store`.`hamburger` (
  `id` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_hamburger_product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_hamburger_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `optical_store`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optical_store`.`drink`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optical_store`.`drink` (
  `id` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_drink_product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_drink_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `optical_store`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optical_store`.`home delivery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optical_store`.`home delivery` (
  `id` INT NOT NULL,
  `order_id` INT NOT NULL,
  `deliveryman_id` INT NOT NULL,
  `time` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_home delivery_order1_idx` (`order_id` ASC) VISIBLE,
  INDEX `fk_home delivery_deliveryman1_idx` (`deliveryman_id` ASC) VISIBLE,
  CONSTRAINT `fk_home delivery_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `optical_store`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_home delivery_deliveryman1`
    FOREIGN KEY (`deliveryman_id`)
    REFERENCES `optical_store`.`deliveryman` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optical_store`.`pick_up`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optical_store`.`pick_up` (
  `id` INT NOT NULL,
  `order_id` INT NOT NULL,
  `time` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pick_up_order1_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `fk_pick_up_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `optical_store`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
