-- MySQL Script generated by MySQL Workbench
-- Thu Sep 28 14:59:57 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema optical_store
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema optical_store
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `optical_store` DEFAULT CHARACTER SET utf8mb3 ;
USE `optical_store` ;

-- -----------------------------------------------------
-- Table `optical_store`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optical_store`.`address` (
  `id` INT NOT NULL,
  `street` VARCHAR(45) NULL DEFAULT NULL,
  `number` VARCHAR(45) NULL DEFAULT NULL,
  `floor` VARCHAR(45) NULL DEFAULT NULL,
  `door` VARCHAR(45) NULL DEFAULT NULL,
  `city` VARCHAR(45) NULL DEFAULT NULL,
  `postal code` INT NULL DEFAULT NULL,
  `country` INT NULL DEFAULT NULL,
  `type` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `optical_store`.`Supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optical_store`.`Supplier` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL COMMENT '\\n',
  `telephone` INT NULL DEFAULT NULL,
  `fax` INT NULL DEFAULT NULL,
  `nif` VARCHAR(45) NULL DEFAULT NULL,
  `address_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Supplier_address1_idx` (`address_id` ASC) VISIBLE,
  CONSTRAINT `fk_Supplier_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `optical_store`.`address` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `optical_store`.`Brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optical_store`.`Brand` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `supplier_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `supplier_id_idx` (`supplier_id` ASC) VISIBLE,
  CONSTRAINT `supplier_id`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `optical_store`.`Supplier` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `optical_store`.`Recommended`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optical_store`.`Recommended` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `optical_store`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optical_store`.`Customer` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `adress` VARCHAR(45) NULL DEFAULT NULL,
  `telephone` INT NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `registration_date` DATE NULL DEFAULT NULL,
  `Recommended_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Customer_Recommended1_idx` (`Recommended_id` ASC) VISIBLE,
  CONSTRAINT `fk_Customer_Recommended1`
    FOREIGN KEY (`Recommended_id`)
    REFERENCES `optical_store`.`Recommended` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `optical_store`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optical_store`.`Employee` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `optical_store`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optical_store`.`Product` (
  `id` INT NOT NULL,
  `graduation-left` VARCHAR(45) NULL DEFAULT NULL,
  `graduation-right` VARCHAR(45) NULL,
  `type` ENUM("metallic", "paste", "floating") NULL DEFAULT NULL,
  `frame_color` VARCHAR(45) NULL DEFAULT NULL,
  `glass_color` VARCHAR(45) NULL DEFAULT NULL,
  `price` DOUBLE NULL DEFAULT NULL,
  `brand_id` INT NOT NULL,
  `stock` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `brand_id_idx` (`brand_id` ASC) VISIBLE,
  CONSTRAINT `brand_id`
    FOREIGN KEY (`brand_id`)
    REFERENCES `optical_store`.`Brand` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `optical_store`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optical_store`.`Order` (
  `id` INT NOT NULL,
  `date` DATE NULL DEFAULT NULL,
  `total_sale` DOUBLE NULL DEFAULT NULL,
  `Employee_id` INT NOT NULL,
  `Customer_id` INT NOT NULL,
  `Product_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Order_Employee1_idx` (`Employee_id` ASC) VISIBLE,
  INDEX `fk_Order_Customer1_idx` (`Customer_id` ASC) VISIBLE,
  INDEX `fk_Order_Product1_idx` (`Product_id` ASC) VISIBLE,
  CONSTRAINT `fk_Order_Customer1`
    FOREIGN KEY (`Customer_id`)
    REFERENCES `optical_store`.`Customer` (`id`),
  CONSTRAINT `fk_Order_Employee1`
    FOREIGN KEY (`Employee_id`)
    REFERENCES `optical_store`.`Employee` (`id`),
  CONSTRAINT `fk_Order_Product1`
    FOREIGN KEY (`Product_id`)
    REFERENCES `optical_store`.`Product` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
